### PR TITLE
Acc test lockability

### PR DESCRIPTION
**Pull request by Raghavendra80**
## PR description
Just SpotlessApply changes.

### CODE REVIEW

**Comment by drinkcoffee** [comment]
This branch was merged into the circle ci branch. As such, all the changes here should now be integrated into master.

**Comment by hmijail** [comment]
So, is this Pull Request no longer valid? If so, we should close it and delete the branch
(by the way, we are accumulating a ton of old branches in our main fork!)

**Comment by drinkcoffee** [comment]
> So, is this Pull Request no longer valid? If so, we should close it and delete the branch
> (by the way, we are accumulating a ton of old branches in our main fork!)

I agree - this pull request has been superseded. I think it should be closed. Do you agree @Raghavendra-PegaSys

**Comment by Raghavendra80** [comment]
Agreed

**Comment by hmijail** [comment]
@Raghavendra-PegaSys , I closed the PR but didn't delete the branch because I'm not sure if it has unmerged work in it. If it doesn't please remember to delete it.

**Comment by Raghavendra80** [comment]
Deleted

**Pull request closed without merging**
